export const ROLES = {
    SUPER_ADMIN: "SUPER_ADMIN",
    ADMIN_CONDOMINIO: "ADMIN_CONDOMINIO",
    PROPIETARIO: "PROPIETARIO",
    AGENTE_SEGURIDAD: "AGENTE_SEGURIDAD"
};

export const ROLES_MAP = {
    1: ROLES.SUPER_ADMIN,
    2: ROLES.ADMIN_CONDOMINIO,
    3: ROLES.PROPIETARIO,
    4: ROLES.AGENTE_SEGURIDAD
};

export const VALID_ROLES = [
    ROLES.SUPER_ADMIN,
    ROLES.ADMIN_CONDOMINIO,
    ROLES.PROPIETARIO,
    ROLES.AGENTE_SEGURIDAD
];