export const ROLES = {
  SUPER_ADMINISTRADOR: "SUPER_ADMINISTRADOR",
  ADMINISTRADOR_CONDOMINIO: "ADMINISTRADOR_CONDOMINIO",
  PROPIETARIO: "PROPIETARIO",
  AGENTE_SEGURIDAD: "AGENTE_SEGURIDAD",
}

export const VALID_ROLES = [
  ROLES.SUPER_ADMINISTRADOR,
  ROLES.ADMINISTRADOR_CONDOMINIO,
  ROLES.PROPIETARIO,
]
